export const AUTH_RESULT_PERSISTED = 'AUTH_RESULT_PERSISTED';
export const USER_INFO_REQUESTED = 'USER_INFO_REQUESTED';
export const PROFILE_SENT = 'PROFILE_SENT';
export const USER_IS_LOGGED_IN_REQUESTED = 'USER_IS_LOGGED_IN_REQUESTED';
export const IS_LOGGED_IN_SENT = 'IS_LOGGED_IN_SENT';
export const AUTH_RESULT_DELETED = 'AUTH_RESULT_DELETED';
